version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:  
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      
      
  acceptance_test_1:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./server
  
  acceptance_test_2:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm test
          working_directory: ./client
   
  docker-mk:
    machine: true
    steps:
      - checkout          
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "izargot" --password-stdin
            sudo docker build ./db -t arturekcicd/node-react-db
            sudo docker push arturekcicd/node-react-db:latest
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "izargot" --password-stdin
            sudo docker build ./server -t arturekcicd/serwer
            sudo docker push arturekcicd/serwer
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "izargot" --password-stdin
            sudo docker build ./client -t arturekcicd/klient
            sudo docker push arturekcicd/klient
            
workflows:
    build-and-test:
      jobs:
        - build:
          filters:
            branches:
              only:
                - master
        - acceptance_test_1:
            filters:
              branches:
                only:
                 - master
            requires:
                - build
        - acceptance_test_2:
            filters:
              branches:
                only:
                 - master
            requires:
                - build
        - docker-mk:
            requires:
              - acceptance_test_1
              - acceptance_test_2
